# server:
#   contextPath: /
#   port: 80
# spring:
#   profiles:
#     active: dev
# mybatis:
#   config-location: classpath:/mybatis-config.xml

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: "000"
    max-active: 20
    man-idle: 8
    min-idle: 8
    initial-size: 10
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.boot.base: DEBUG
    org.apache: ERROR